//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singlife
{


    public partial class EditSubmitClaims
    {

        protected global::System.Web.UI.WebControls.TextBox diagnosisDate;

        protected global::System.Web.UI.WebControls.TextBox treatmentCountry;

        protected global::System.Web.UI.WebControls.TextBox cancerType;

        protected global::System.Web.UI.WebControls.RadioButton firstYes;

        protected global::System.Web.UI.WebControls.RadioButton firstNo;

        protected global::System.Web.UI.WebControls.RadioButton treatmentYes;

        protected global::System.Web.UI.WebControls.RadioButton treatmentNo;

        protected global::System.Web.UI.WebControls.RadioButton confirmedYes;

        protected global::System.Web.UI.WebControls.RadioButton confirmedNo;

        protected global::System.Web.UI.WebControls.TextBox treatmentDate;

        protected global::System.Web.UI.WebControls.TextBox hospital;

        protected global::System.Web.UI.WebControls.DropDownList therapyType;

        protected global::System.Web.UI.WebControls.RadioButton screeningYes;

        protected global::System.Web.UI.WebControls.RadioButton screeningNo;

        protected global::System.Web.UI.WebControls.CheckBox declaration;

        protected global::System.Web.UI.WebControls.Literal litTreatmentFile;

        protected global::System.Web.UI.WebControls.Literal litScreeningFile;

        protected global::System.Web.UI.WebControls.Literal litOtherFiles;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.FileUpload fuTreatment;

        protected global::System.Web.UI.WebControls.FileUpload fuScreening;

        protected global::System.Web.UI.WebControls.FileUpload fuOthers;

        protected global::System.Web.UI.WebControls.Button btnUpdateClaim;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
